[package]
name = "trs80m1-rs"
version = "0.2.0"
authors = ["Marek Benc <dusxmt@gmx.com>"]

[dependencies]
sdl2 = "0.31"
time = "0.1"
getopts = "0.2"

[dependencies.pancurses]
version = "0.16"
features = ["win32"]
